[package]
name = "tcc-host-sqlite"
version = "26.10.2"
edition = "2021"
license = "BUSL-1.1"
repository = "https://github.com/trigora-dev/tcc-engine"
description = "SQLite host for TCC executions"

[dependencies]
libc = "0.2"
rusqlite = { version = "0.32", features = ["bundled"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tcc-core = { version = "26.10.2", path = "../tcc-core" }
tcc-host = { version = "26.10.2", path = "../tcc-host" }
tcc-ir = { version = "26.10.2", path = "../tcc-ir" }
tcc-state = { version = "26.10.2", path = "../tcc-state" }

[[bin]]
name = "tcc-host-sqlite"
path = "src/bin/worker.rs"
